### ISSUE TITLE
Document the new saltboot behavior in SUMA

### ISSUE THREAD

**Issue by hustodemon** [SUSE/doc-susemanager#169]
Just creating this card, so we don't forget to document this:
- https://github.com/SUSE/spacewalk/pull/5415
- https://github.com/SUSE/spacewalk/pull/5673 
- https://github.com/SUSE/spacewalk/pull/5845.

At the moment I don't know how much we need to document (and even where :smile: the feature overlaps with Retail). I need to discuss this with @aaannz and @jcayouette .

**Comment by Loquacity** [comment]
Moved to https://github.com/SUSE/spacewalk/issues/6556
