### ISSUE TITLE
Adoc Style Guide / Getting started improvements

### ISSUE THREAD

**Issue by jcayouette** [SUSE/doc-susemanager#210]
We need to clarify when to use db5 replacement macros and which ones are available.

Create a table in the guide adding the available geekodoc macros, for example:

[filename]``/etc/hosts``
[literal]``This is a literal string``

**Comment by Loquacity** [comment]
There's a good start here, we just need to remember to keep it updated: https://github.com/SUSE/doc-susemanager/wiki/asciidoc-getting-started
