### ISSUE TITLE
Retail: Document the FQDN matching on empty profile registration

### ISSUE THREAD

**Issue by hustodemon** [SUSE/doc-susemanager#247]
https://github.com/SUSE/spacewalk/issues/6059

**Comment by Loquacity** [comment]
This is mentioned in the Formulas chapter:

`When you are configuring the bind formula for a branch server with a dedicated internal network, check that you are using the same fully qualified domain name (FQDN) on both the external and internal branch networks.
If the FQDN does not match on both networks, the branch server will not be recognized as a proxy server.`
