### ISSUE TITLE
Salt Formulas: Wrong custom formula form path in the file directories example

### ISSUE THREAD

**Issue by teclator** [SUSE/doc-susemanager#300]
[Best Practices - FIle Overview description](https://www.suse.com/documentation/suse-manager-3/singlehtml/book_suma_best_practices_31/book_suma_best_practices_31.html#best.practice.salt.formulas.filedir) contains some confusing documentation examples about custom formula directories, i have added just two comments for trying to make it more clear.

## Metadata Directory

    Custom metadata (information) need to be placed in:

    # Replacing `custom` by `custom-formula-name` as it is already documented in other examples probably would be less confusing
    /srv/formula_metadata/custom/

All custom folders located in the following directories needs to contain a form.yml file. These files are detected as form recipes and may be applied to groups and systems from the Web UI:

    # Is this path correct? it seems that `salt` was added by error or confusion with the states directories
    /srv/salt/formula_metadata/custom-formula-name/form.yml

**Comment by joesusecom** [comment]
Both observations are correct. Please fix.

**Comment by Loquacity** [comment]
Moved to https://github.com/SUSE/spacewalk/issues/6607
