### ISSUE TITLE
Documentaion for Pillar setting of RPM endpoint

### ISSUE THREAD

**Issue by admd** [SUSE/doc-susemanager#331]
As there is no existing chapter (https://github.com/SUSE/spacewalk/issues/6890) where I should add this information, instead of creating the PR, I am creating this issue. 

## Background 
In typical configurations the SUSE Manager Server is the Salt Master and also the download endpoint for packages (eg. RPM files) and repository metadata. Also it has exactly one, well-defined, FQDN. There is also the possibility of having a SUSE Manager Proxy - in this case the download endpoint FQDN is the Proxy's FQDN.

Thus zypper's `.repo` generated files look like this:

```
suma-32-min-sles12sp3:~ # cat /etc/zypp/repos.d/susemanager\:channels.repo
# Channels managed by SUSE Manager
# Do not edit this file, changes will be overwritten
#

[susemanager:test-channel-x86_64]
name=Test-Channel-x86_64
enabled=1
autorefresh=1
baseurl=https://suma-32-pxy.prv.suse.net:443/rhn/manager/download/test-channel-x86_64?eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Nzk2Nzg5NzUsImlhdCI6MTU0ODE0Mjk3NSwibmJmIjoxNTQ4MTQyODU1LCJvcmciOjEsImp0aSI6IldyekNKN3BuUkVPTWlsdUNoYzNjNmciLCJvbmx5Q2hhbm5lbHMiOlsidGVzdC1jaGFubmVsLXg4Nl82NCJdfQ.k4FY7WfEbPqy75DPxH2daPOfmAMsFrjdiRIIjhq8oTQ
type=rpm-md
gpgcheck=0
repo_gpgcheck=0
pkg_gpgcheck=1
```

Note **suma-32-pxy.prv.suse.net:443** as the host in `baseurl`.

There are more complicated scenarios in which the `baseurl` might legitimately be customized:
 - Load balancers for availability reasons
 - Caching proxies for performance reasons
 - entire CDNs to overcome internal networking problems, especially bandwidth management
 - atypical naming schemes with more than one valid FQDNs, etc.

This feature allows customers to set a custom name and protocol to download packages and repository metadata to accommodate for all these cases. It is the customer's responsibility to make sure the specified endpoints serve files as the original SUSE Manager Server or Proxy would.

More details:
 -  https://github.com/SUSE/spacewalk/issues/6496
 - https://github.com/SUSE/spacewalk/pull/6881

## Documentaion

Following details needs to be documented which customer can consult it order to achive the above mentioned feature.

---
There are three different but related pillars have been introduced in order to set the basurl in a repository file. These are the following.

-  pkg_download_point_protocol
-  pkg_download_point_host
-  pkg_download_point_port

If these pillars would not be defined, then the existing default values would be used in the baseurl. Currently, default values are `https` for protocol, `fqdn` , of the host where susmanager manager is running, as host and `443` as port. To override these values, followings steps needs to be taken.

**1**- Create a top.sls in /srv/pillar/top.sls  An example is given below
```
base:
  '*':
    - pkg_download_points
```
  
In the above example, it is stated that in the base environment, all(*)minions will have the pillar data found in the rpm_download_points pillar available to them.

Compound matchers can also be used to target minions using different criteria https://docs.saltstack.com/en/latest/topics/targeting/compound.html . 

**Note:** Pillar glob to target systems in top.sls is currently not working. A high-severity issue in salt already exists https://github.com/saltstack/salt/issues/26727

**2**- Next comes the pkg_download_points.sls file itself. As an example I used grains to target different minions based on their fqdn.
```

{% if grains['fqdn'] == 'minion1.tf.local' %}
      pkg_download_point_protocol: http
      pkg_download_point_host: proxy1.com
      pkg_download_point_port: 444
{% elif grains['fqdn'] == 'minion2.tf.local'' %}
      pkg_download_point_protocol: https
      pkg_download_point_host: proxy2.com
      pkg_download_point_port: 445
{%else%}
      pkg_download_point_protocol: http
      pkg_download_point_host: proxy3.com
      pkg_download_point_port: 446
{% endif %}
```
In Suse Manager, a number of systems can be added to a system group and then it is possible to target them using `group_ids` pillar. `group_ids` pillar is defined as an external pillar along side others pillars like `channels`, `contact_,method` etc.

To use external pillar like `group_ids` in `pkg_download_points.sls`, user need to set `ext_pillar_first` to `True` in salt master config and restart the master. After this, user can do something like this to set pillar values based on group_ids for example.

```
{% if pillar['group_ids'] is defined and 8 in pillar['group_ids'] %}
     pkg_download_point_protocol: https
     pkg_download_point_host: proxy1.com
     pkg_download_point_port: 444
{%else%}
     pkg_download_point_protocol: ftp
     pkg_download_point_host: proxy2.com
     pkg_download_point_port: 445
{%- endif %}
```

In the above example, all the systems with `group_ids` 8  will be redirected to proxy1 in order to download the packages.

**Comment by Loquacity** [comment]
Please review https://github.com/SUSE/doc-susemanager/pull/366

**Comment by moio** [comment]
Addressed.
