### ISSUE TITLE
cobbler changed directories

### ISSUE THREAD

**Issue by mcalmer** [SUSE/doc-susemanager#379]
Kickstart templates changed the directory.
We need to check if we have references to the old dirs somewhere in the docs.
They need to be replaced.

```
/var/lib/rhn  => /var/lib/cobbler
/var/lib/rhn/kickstarts  => /var/lib/cobbler/templates
```

Reference: https://github.com/uyuni-project/uyuni/pull/736

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/doc-susemanager/issues/379
