### ISSUE TITLE
cobbler API change

### ISSUE THREAD

**Issue by mcalmer** [SUSE/doc-susemanager#380]
The download endpoint for a profile has changed.
```
/cblr/svc/op/ks/profile/... => /cblr/svc/op/autoinstall/profile/...
```
This is visible in PXE boot and Groub config. So maybe this path also appear somewhere in the manual. We need to check.

Check for something like this:

autoyast=http://<IP>/cblr/svc/op/ks/profile/PROFILE:ORGID:NAME

Reference: https://github.com/uyuni-project/uyuni/pull/741

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/7415
