### ISSUE TITLE
Live patching support for SLES 15

### ISSUE THREAD

**Issue by cbbayburt** [SUSE/doc-susemanager#383]
In SLES 15, there are some changes in the live patching feature which must be reflected to the documentation:

 - Live patching versions: prefix renamed from "kgraft_" to "livepatch_"
 - Package names are renamed from "kgraft" to "kernel-livepatch"
 - The `kgr` tool is renamed to `klp`

In general, we should not use the name "kgraft" anywhere for SLES 15.
I think it makes sense to separate the guides for SLES 12 and 15, since 12 will stay as-is.

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/7425
