### ISSUE TITLE
Documentation for Salt rate-limiting feature

### ISSUE THREAD

**Issue by chiaradiamarcelo** [SUSE/doc-susemanager#430]
We should introduce the documentation regarding the new Salt rate-limiting feature ("Batching" in Salt jargon).

Given that Salt can run commands in parallel on a huge number of minions, and those commands might generate load on potentially unrelated parts of the user's infrastructure (eg, Web Servers), this feature limits the amount of minions an Action is run in parallel.

The following parameters should be set in order for this feature to perform:

- Salt Batch Size: Upper limit to the number of minions that execute a single Action concurrently. Lowering this value prevents thundering-herd effects from Action execution but can decrease overall performance as the overall level of parallelization is reduced. This is translated to the `--batch-size` Salt option.
The default value is 200, and it can be overridden by setting the variable "java.salt_batch_size" in "/etc/rhn/rhn.conf" file.

- Salt Batch Delay: Delay, in seconds, before a new batch is scheduled. After the first batch is scheduled with a size up to java.salt_batch_size, subsequent batches will contain a smaller number of minions: the exact count will be equal to the number of minions completing before java.salt_batch_delay expires. Higher values will typically result in bigger batches with a lower CPU and I/O load on the Salt Master, while smaller values will typically result in smaller batches with higher CPU and I/O load on the Salt Master.
The default value is 1.0, and it can be overridden by setting the variable "java.salt_batch_delay" in "/etc/rhn/rhn.conf" file.

- Salt presence ping timeout: Timeout in seconds of the presence ping performed in Salt Minions during salt batch calls.
The default value is 4, and it can be overridden by setting the variable "java.salt_presence_ping_timeout" in "/etc/rhn/rhn.conf" file.

- Salt presence ping gather job timeout: Timeout in seconds for gathering the presence ping jobs performed in Salt Minions during salt batch calls.
The default value is 1, and it can be overridden by setting the variable "java.salt_presence_ping_gather_job_timeout" in "/etc/rhn/rhn.conf" file.

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/7652
