### ISSUE TITLE
Traditional packages were renamed

### ISSUE THREAD

**Issue by mcalmer** [SUSE/doc-susemanager#458]
With release of Uyuni we renamed some packages. Mainly packages of the traditional client stack, but they are sometimes named also in the docs.

The doc should use the new names and maybe add a hint somewhere that packages got renamed (this will be also in the release notes)

"rhncfg" => "mgr-cfg"
"rhncfg-actions" => "mgr-cfg-actions"
"rhncfg-client" => "mgr-cfg-client"
"rhn-virtualization-host" => "mgr-virtualization-host"
"osad" => "mgr-osad"
"rhnsd" => "mgr-daemon"

**Comment by Loquacity** [comment]
This was tracked and completed in https://github.com/SUSE/spacewalk/issues/6555
