### ISSUE TITLE
Add reference of github repo on https://opensource.suse.com

### ISSUE THREAD

**Issue by vmoutoussamy** [SUSE/doc-susemanager#483]
Hi, 

It would be cool if you could reference "https://github.com/SUSE/doc-susemanager" somewhere on "https://opensource.suse.com/doc-susemanager/suse-manager/rc1/index-suma.html".

Something like a github logo at the very bottom of every page?
Of course this is for helping people find where to fill issue or make PR for the documentation ; ).

Regards,

**Comment by jcayouette** [comment]
Yes this already exists. However I need to adjust our UI for the opensource site. Thanks!

**Comment by Loquacity** [comment]
If you click the "edit this page" button, it takes you to the repo.

![image](https://user-images.githubusercontent.com/3914967/58388566-eabec800-8063-11e9-887c-ab19cf69fffc.png)

**Comment by jcayouette** [comment]
The UI has been adjusted. Thanks for the report Vincent.
