### ISSUE TITLE
Top link not working on each guide

### ISSUE THREAD

**Issue by vmoutoussamy** [SUSE/doc-susemanager#484]
If I'm in any "Available Draft Documentation" listed on "https://opensource.suse.com/doc-susemanager/suse-manager/rc1/index-suma.html" and click on the very top "SUSE Manager // Documentation" link, I get an error: "Page Not Found".

**Comment by Loquacity** [comment]
This is working for me with the 4.0 docs.

**Comment by vmoutoussamy** [comment]
Still not working for me for instance on https://opensource.suse.com/doc-susemanager/suse-manager/4/upgrade/upgrade-overview.html. But now I also see a big fat twitter logo but still "Page Not Found" at the end of the page. I'm really talking about "SUSE Manager // Documentation".

**Comment by Loquacity** [comment]
Ah, OK, it works from the main page, but not if you're on any other page! This looks like a job for @jcayouette

**Comment by jcayouette** [comment]
Yes, this has to do with indexing, if indexing is not done when uploading a new version of the docs, of course the links contained in the algolia database will not match the search pages :). I updated a new version yesterday, wiped the algolia DB and rebuilt. It should be working for you now. Let me know if you find any other issues. In the coming weeks Ill switched to lunr.js and we can move away from the distributed references.

**Comment by Loquacity** [comment]
Seems to  be working reliably for me now. @vmoutoussamy can you please confirm?

**Comment by vmoutoussamy** [comment]
I confirm this is fixed. Thanks.
