### ISSUE TITLE
New directory for salt-formulas

### ISSUE THREAD

**Issue by admd** [SUSE/doc-susemanager#487]
SUSE Manager can handle now new directory for salt-formulas. More background Information 
https://github.com/SUSE/spacewalk/issues/7632 and this PR takes care of this change.
https://github.com/SUSE/spacewalk/pull/7921

IIUC old directory `/usr/share/susemanager/formulas`,  we'll remove in the next major release. 

Question is, should we document it that it will be removed, maybe somewhere here
https://github.com/SUSE/doc-susemanager/blob/d3f7423b76b5e3edd63bfcbcd27e00db66badb5d/modules/salt/pages/salt-formulas.adoc

and maybe we should also mention that another install location is supported.

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/7937
