### ISSUE TITLE
Deprecated information

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-susemanager#50]
The SUSE Manager 3 Reference Manual still references up2date which was the old package manager used by Red Hat on RHEL 4 in 2005 and never used in a SUSE product. Any reference to it should probably be changed to Zypper or Yum. See https://www.suse.com/documentation/suse-manager/singlehtml/book_suma_reference_manual/book_suma_reference_manual.html for examples.

**Comment by jcayouette** [comment]
The only reference I found for up2date was for staging, I believe this is still relevant but I will check with devs.

**Comment by jcayouette** [comment]
Ok, thanks!

**Comment by jcayouette** [comment]
Will touch up once the adoc sources are clean.

**Comment by Loquacity** [comment]
Please review: https://github.com/SUSE/doc-susemanager/pull/294
