### ISSUE TITLE
Error in port list

### ISSUE THREAD

**Issue by jcayouette** [SUSE/doc-susemanager#54]
I have noticed an error in the port table in the SUSE Manager documentation:

link: https://www.suse.com/documentation/suse-manager-3/book_suma_getting-started_31/data/sect1_2_chapter_book_suma_getting-started_31.html

Correction:

In the port table:

Incorrect: 4505 and 4506 are listed as inbound and outbound

Correct: 4505 and 4506 are inbound only
Notes: The salt master never initiates a connection to the minions.

Richard

**Comment by keichwa** [comment]
also fixed in the 3.1 maint branch
