### ISSUE TITLE
SUSE Linux Enterprise 15 (when available)

### ISSUE THREAD

**Issue by pmckeithSUSE** [SUSE/doc-susemanager#576]
Small edit on this page: https://www.suse.com/documentation/suse-manager-4/4.0/suse-manager/client-configuration/disconnected-setup.html 

Remove "(when available)" from the line:
  SUSE Linux Enterprise 15 (when available)

**Comment by keichwa** [comment]
thanks for feedback!

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/8359
