### ISSUE TITLE
Update 'Terminal Names' page

### ISSUE THREAD

**Issue by aaannz** [SUSE/doc-susemanager#590]
**Please update retail 'Terminal Names' page based on the following text.**
**Also there seems to be typo in documentation index where terminal page is not accessible and shown only as `retail-ternminal-names.adoc`**

Terminals can get different system names depending on various settings.

Default terminal naming is to use HW Type based names.
However if Saltboot boot mechanism detects that the IP address assigned to the terminal can be resolved to hostname, Saltboot will use system name based on this hostname. This behaviour can be disabled by setting `DISABLE_HOSTNAME_ID` to 1 in PXE formulas Kernel command line options for given Branch Server proxy.

## HW Type based names

Hardware type based name follows pattern:

```$BranchID.$Manufacturer-$ProductName-$SerialNumber-$UniqueSuffix```

where

`$BranchID` is the ID of Branch Server proxy to which this terminal belongs. This value is configured in PXE formula of given Branch Server proxy

`$Manufacturer` and `$ProductName` are SMBios information about the particular hardware

`$SerialNumber` is SMBios information, if it does not exists, this entry is omitted together with prefixing '-'

`$UniqueSuffix` are first four characters of generated machine ID. This option can be disabled by setting `DISABLE_UNIQUE_SUFFIX` to 1 in PXE Kernel command line options of given Branch Server proxy.

## Hostnames based names

Hostname based names follows pattern:

```$BranchID.$FQDN-$UniqueSuffix```

where

`$BranchID` is the ID of Branch Server proxy to which this terminal belongs. This value is configured in PXE formula of given Branch Server proxy

`$FQDN` is fully qualified domain name of terminal

`$UniqueSuffix` are first four characters of generated machine ID. This option can be disabled by setting `DISABLE_UNIQUE_SUFFIX` to 1 in PXE Kernel command line options of given Branch Server proxy.

## Assigning hostnames to Retail terminals

Depending on the particular configuration there are multiple ways how to assign terminal hostname and resolving IP address. In this guide only scenario when DNS and DHCP services are manager by Branch Server proxy is considered.

For terminal to have a static hostname terminal also has to have static IP address to which this hostname resolves.

### Using Formulas to assign IP address and hostname

1) Assign terminal static IP address in DHCP formula for given Branch Server proxy
In DHCP formula find 'Hosts with Static IP Addresses (with Defaults from Subnet)' and click 'Add Item'
In new form enter
* Hostname
* IP address
* Hardware Type and Address - use format 'ethernet $terminal_mac_address'
You can enter additional terminals by clicking 'Add Item'. Click 'Save Formula' after editing.

2) Assign terminal hostname and its IP address in Bind formula for given Branch Server proxy
In non-reverse zone find 'Records' and then 'A' and click 'Add Item'
In new form enter
* Hostname
* IP address assigned to terminal in previous step
You can enter additional terminals by clicking 'Add Item'. Click 'Save Formula' after editing.

After highstate is applied on given Branch Server, terminal should get the new hostname. If the terminal was already registered in SUSE Manager using HW type based name, this registration must be deleted and terminal reregistered witch new system name.

### Using command line interface `retail_yaml` tool

1) Export up-to-date YAML by calling `retail_yaml --to-yaml retail.yaml`
2) Edit the YAML file and navigate to the end of given Branch Server proxy section or find 'terminals' section under given Branch Server proxy if already present.
3) If 'terminals' section is not yet present, add it.
4) Under this 'terminals' section terminals information can be appended in the format:
```yaml
$hostname:
        IP: $IP_address
        hwAddress: $MAC_address
        hwtype: $HWTYPE_Group_name_without_HWTYPE:_prefix
```
See https://opensource.suse.com/doc-susemanager/suse-manager/retail/retail-mass-config.html#_example_yaml_file_for_mass_configuration for details

5) Import back modified YAML file using command `retail_yaml --from-yaml retail.yaml`

After highstate is applied on given Branch Server, terminal should get the new hostname. If the terminal was already registered in SUSE Manager using HW type based name, this registration must be deleted and terminal reregistered witch new system name.

**Comment by keichwa** [comment]
Ondřej Holeček <notifications@github.com> writes:

> **Please update retail 'Terminal Names' page based on the following text.**
> **Also there seems to be typo in documentation index where terminal page
> is not accessible and shown only as `retail-ternminal-names.adoc`**

https://opensource.suse.com is outdated :-(

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nürnberg)

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/8340
