### ISSUE TITLE
Wrong command specified in the document while the document source is ok

### ISSUE THREAD

**Issue by vzhestkov** [SUSE/doc-susemanager#628]
https://www.suse.com/documentation/suse-manager-4/4.0/suse-manager/upgrade/migrate-3x-4x.html
This document in the section "Setting Up the Target Machine", in point 2 contains the command: yast2 susemanagersetup
While the correct one is: yast2 susemanager_setup
I've checked with the document source on the git, but there is no such mistake. It seems the misquoting on the site or just the data on the site is not in sync.

**Comment by keichwa** [comment]
Yes, in the meantime, Don committed a fix:

commit 163d7aadf4245fe2bc2917f7aa0686b92a261df0
Author: dvosburg <don@vosburgs.org>
Date:   Mon Jul 1 22:59:52 2019 -0400

    Update migrate-3x-4x.adoc
    
    Missing underscore

======================================================

I hope we soon can update the documentation on suse.com/documentation @jcayouette @Loquacity

**Comment by Loquacity** [comment]
It's correct on the opensource.suse.com site, which was refreshed yesterday: https://opensource.suse.com/doc-susemanager/suse-manager/upgrade/migrate-3x-4x.html#bp.sec.mgr.migration.setup.target

This will filter through to the other published locations as they are updated.
