### ISSUE TITLE
Task token cleanup unlisted

### ISSUE THREAD

**Issue by jcayouette** [SUSE/doc-susemanager#74]
https://docreview.nue.suse.com/assets/docs/ref.webui.admin.html#ref.webui.admin.schedules 
<- token cleanup is not listed here, maybe we should add it?

**Comment by Loquacity** [comment]
Looks like it's there now: https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-reference/html/book.suma.reference.manual/ref.webui.admin.html#ref.webui.admin.schedules
