### ISSUE TITLE
Content Lifecycle Management examples menu items missing/different

### ISSUE THREAD

**Issue by rkoktan** [SUSE/doc-susemanager#833]
I'm following this section in my lab to learn CLM in SUMA 4.0.2...
https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/administration/content-lifecycle-examples.html
... and the first section to create a filter has me stumped... when I "Create Filter", I do not see Filter Type "Patch (Issue date)", nor do I see a "Matcher" field, I see "Package (contains Name)", "Package (matches NEVRA)", and "Package (matches Advisory Name)"

**Comment by mcalmer** [comment]
The docs are newer then the released code . You will get the new filters when the next Maintenance Update is released.  Will take a few weeks.

**Comment by Loquacity** [comment]
Thanks @mcalmer
