### ISSUE TITLE
Missing page migrate-3x-4x.html

### ISSUE THREAD

**Issue by mmeiste** [SUSE/doc-susemanager#870]
seems I found an issue within SUSE Manager documentation. I found this page:
https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/upgrade/migrate-3x-4x.html

But I cannot find any link from upgrade guide to this? Only the search brings this up.

**Comment by Loquacity** [comment]
Hi Markus, as mentioned on rocket chat, we are aware of this issue, and it is fixed in our latest version. That version will be updated on the website in the next couple of days.
