### ISSUE TITLE
      SUSE Manager     Salt SSH Push

### ISSUE THREAD

**Issue by mmeiste** [SUSE/doc-susemanager#876]
Salt SSH Push seemsto be not in any guide:
    SUSE Manager /  Salt SSH Push

https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/architecture/salt-ssh-push.html

**Comment by Loquacity** [comment]
That is part of our Architecture Guide, which is currently incomplete and, therefore, de-linked (although the pages are still served, as you found). We do have this in Contact Methods in the Client Config Guide, though: https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/client-configuration/contact-methods.html#_push_via_salt_ssh Does that resolve the problem?

**Comment by mmeiste** [comment]
I just found that unlinked page, if it's expected, please go ahead and close.

**Comment by Loquacity** [comment]
Thanks @mmeiste

**Comment by keichwa** [comment]
I think we must not "publish" unlinked pages.  Those pages are probably unlinked for a reason.

I think these pages are spurious left-overs from a previous publication.

**Comment by Loquacity** [comment]
The only other option, I think, is to remove them from the repo completely, and I don't really want to lose that information. Especially since, in this case, the Arch Guide will eventually be published. Might need @jcayouette to weigh in with options here.
