### ISSUE TITLE
Both links in step 8 on the wiki entry are broken

### ISSUE THREAD

**Issue by mstublefield** [SUSE/doc-susemanager#916]
Thanks for putting this together! I think we'll need it soon. I was looking through it and it appears that these links are broken, so I wanted to bring them to your attention.

https://github.com/SUSE/doc-susemanager/wiki/Setup-Algolia-Search-with-Antora#add-search-to-your-antora-ui

**Comment by Loquacity** [comment]
Hi @mstublefield Thanks for the report. We're not using Algolia search any more, so this wiki is deprecated. You can find the updated instructions for our docs in https://github.com/uyuni-project/uyuni-docs/wiki. If you're looking specifically for Algolia documentation, I would start here: https://www.algolia.com/doc/. Hope that helps!
