### ISSUE TITLE
missing oraclelinuxX-client-tools in https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/

### ISSUE THREAD

**Issue by milari** [SUSE/doc-susemanager#921]
Hi, 
I've tried to use uyuni to manage also an oraclelinux7 vm, so I found what in subject.
I've used "stable" branch.
Please, let me know.
Thanks,
M.

**Comment by ktsamis** [comment]
You need to use [the centos 7 repo here](https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/) see the [project page here](https://www.uyuni-project.org/pages/stable-version.html). Also this repo is not the right one. See from the same project page that the repo for uyuni issues is [here](https://github.com/uyuni-project/uyuni/issues)
